// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://mekpdfitklbmsyzvijtl.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1la3BkZml0a2xibXN5enZpanRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5Mzg4MzQsImV4cCI6MjA3MzUxNDgzNH0.JqtTSKCJOmJCFpME3-mwjygXUb6W3uZiphjpQ8nVaQ0';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
